version: '3.9'

services:
  nestjs-app:
    build: ./node-nestjs-app
    container_name: nestjs-app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - ./node-nestjs-app:/app
    depends_on:
      - flask-app

  flask-app:
    build: ./python-flask-app
    container_name: flask-app
    ports:
      - "3001:3000"
    environment:
      FLASK_ENV: development
    volumes:
      - ./python-flask-app:/app
