# Docker Compose para levantar la app NestJS y la app Flask en contenedores separados

services:
  # -------------------------------
  # Servicio de la aplicación NestJS
  # -------------------------------
  nestjs-app:
    build: ./node-nestjs-app          # Ruta del Dockerfile de NestJS
    container_name: nestjs-app        # Nombre del contenedor
    ports:
      - "3001:3000"                   # Mapea puerto 3001 en host -> 3000 en contenedor
    environment:
      NODE_ENV: development           # Variable de entorno para NestJS
    depends_on:
      - flask-app                      # Espera a que flask-app esté listo

  # -------------------------------
  # Servicio de la aplicación Flask
  # -------------------------------
  flask-app:
    build: ./python-flask-app         # Ruta del Dockerfile de Flask
    container_name: flask-app         # Nombre del contenedor
    ports:
      - "3000:3000"                   # Mapea puerto 3000 en host -> 3000 en contenedor
    environment:
      FLASK_ENV: development          # Variable de entorno para Flask
